// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVf7gp80FZ9e0q6r-MH2pswGAkoE37xKs',
    appId: '1:611597196765:web:65f206b762d9cea3f32a34',
    messagingSenderId: '611597196765',
    projectId: 'mis-lab3-f7906',
    authDomain: 'mis-lab3-f7906.firebaseapp.com',
    databaseURL: 'https://mis-lab3-f7906-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mis-lab3-f7906.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiquUtj-1rdLm3XeSsA64xKVv-CUFtj1c',
    appId: '1:611597196765:android:d856e0a35c841d2cf32a34',
    messagingSenderId: '611597196765',
    projectId: 'mis-lab3-f7906',
    databaseURL: 'https://mis-lab3-f7906-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mis-lab3-f7906.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo8C0mjztHb5kd_QZpDuXFTl8v81ZQKow',
    appId: '1:611597196765:ios:4376bfbe6b85a9f8f32a34',
    messagingSenderId: '611597196765',
    projectId: 'mis-lab3-f7906',
    databaseURL: 'https://mis-lab3-f7906-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mis-lab3-f7906.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo8C0mjztHb5kd_QZpDuXFTl8v81ZQKow',
    appId: '1:611597196765:ios:4376bfbe6b85a9f8f32a34',
    messagingSenderId: '611597196765',
    projectId: 'mis-lab3-f7906',
    databaseURL: 'https://mis-lab3-f7906-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mis-lab3-f7906.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVf7gp80FZ9e0q6r-MH2pswGAkoE37xKs',
    appId: '1:611597196765:web:137183fdb58b2c26f32a34',
    messagingSenderId: '611597196765',
    projectId: 'mis-lab3-f7906',
    authDomain: 'mis-lab3-f7906.firebaseapp.com',
    databaseURL: 'https://mis-lab3-f7906-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mis-lab3-f7906.firebasestorage.app',
  );
}
